### ISSUE TITLE
Git_Tag is wrong, here are the right tag

### ISSUE THREAD

**Issue by zcc2xj** [cg3hci/HexBox#15]
# fprotais/hexsmoothing
if (HMP_ENABLE_ALT_PROJ)
    add_compile_definitions(HMP_ENABLE_ALT_PROJ)
    FetchContent_Declare (
        fprotais
        GIT_REPOSITORY "https://github.com/fprotais/hexsmoothing"
        GIT_TAG "e31c4d862f31e1099238472504777bf50836a18b"
        GIT_SHALLOW TRUE
        GIT_PROGRESS TRUE
    )
    FetchContent_MakeAvailable (fprotais)
endif()

# cinolib
set (CINOLIB_HEADER_ONLY OFF)
set (CINOLIB_USES_OPENGL_GLFW_IMGUI ON)
FetchContent_Declare (
    cinolib
    GIT_REPOSITORY "https://github.com/francescozoccheddu/cinolib.git"
    GIT_TAG "3ff25510be94860dbd44d6b0e6296c36a3080428"
    GIT_SHALLOW TRUE
    GIT_PROGRESS TRUE
)
FetchContent_MakeAvailable (cinolib)

**Comment by francescozoccheddu** [comment]
Hi,
thank you for reporting this! 😉
It should be fixed now.

**Comment by zcc2xj** [comment]
> Hi, thank you for reporting this! 😉 It should be fixed now.

thank you all
