### ISSUE TITLE
Ctrl+MouseLeft can't select multi faces

### ISSUE THREAD

**Issue by zcc2xj** [cg3hci/HexBox#16]
According to "https://github.com/cg3hci/HexBox/tree/master/tutorials.md"
I find that Ctrl+MouseLeft can't select multi faces, so there is no way to "Extrusion of two adjacent faces in a convex configuration" etc.
**_For cmake -DCMAKE_BUILD_TYPE=Debug , there are several warnings, but no warnig in command of "cmake --build ."_**
###
###
#############
[100%] Built target eigen-populate
-- Performing Test standard_math_library_linked_to_automatically
-- Performing Test standard_math_library_linked_to_automatically - Success
-- Standard libraries to link to explicitly: none
CMake Warning (dev) at zcc_build/_deps/eigen-src/CMakeLists.txt:141 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake   
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.                                  
                                                                             
  For compatibility with older versions of CMake, option is clearing the     
  normal variable 'EIGEN_BUILD_PKGCONFIG'.                                   
This warning is for project developers.  Use -Wno-dev to suppress it.        
                                                                             
-- Performing Test COMPILER_SUPPORT_WERROR
-- Performing Test COMPILER_SUPPORT_WERROR - Success
-- Performing Test COMPILER_SUPPORT_pedantic
-- Performing Test COMPILER_SUPPORT_pedantic - Success
######################
-- Performing Test COMPILER_SUPPORT_OPENMP
-- Performing Test COMPILER_SUPPORT_OPENMP - Success
CMake Warning (dev) at zcc_build/_deps/eigen-src/CMakeLists.txt:475 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake   
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.                                  
                                                                             
  For compatibility with older versions of CMake, option is clearing the     
  normal variable 'EIGEN_BUILD_DOC'.                                         
This warning is for project developers.  Use -Wno-dev to suppress it.        
                                                                             
-- Found unsuitable Qt version "5.15.3" from /usr/bin/qmake
CMake Warning (dev) at zcc_build/_deps/eigen-src/CMakeLists.txt:482 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake   
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.                                  
                                                                             
  For compatibility with older versions of CMake, option is clearing the     
  normal variable 'EIGEN_BUILD_TESTING'.                                     
This warning is for project developers.  Use -Wno-dev to suppress it.        
                                                                             
-- The Fortran compiler identification is GNU 11.4.0
CMake Warning (dev) at zcc_build/_deps/eigen-src/CMakeLists.txt:496 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake   
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.                                  
                                                                             
  For compatibility with older versions of CMake, option is clearing the     
  normal variable 'EIGEN_BUILD_BLAS'.                                        
This warning is for project developers.  Use -Wno-dev to suppress it.        
                                                                             
CMake Warning (dev) at zcc_build/_deps/eigen-src/CMakeLists.txt:497 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake   
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.                                  
                                                                             
  For compatibility with older versions of CMake, option is clearing the     
  normal variable 'EIGEN_BUILD_LAPACK'.                                      
This warning is for project developers.  Use -Wno-dev to suppress it.        
                                                                             
-- Found unsuitable Qt version "5.15.3" from /usr/bin/qmake
-- Qt4 not found, so disabling the mandelbrot and opengl demos
-- Could NOT find CLANG_FORMAT: Found unsuitable version "0.0", but required is exact version "9" (found CLANG_FORMAT_EXECUTABLE-NOTFOUND)
-- 
-- Configured Eigen 3.4.90
-- 
-- Populating stb
-- Configuring done
-- Generating done
### _#####################################
For cmake -DCMAKE_BUILD_TYPE=Release , there is no warning, but several warnigs in command of "cmake --build ."
###
###_
[ 33%] Building CXX object _deps/cinolib-build/CMakeFiles/cinolib.dir/include/cinolib/io/io_utilities.cpp.o                                               
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/io_utilities.cpp: In function ‘bool cinolib::seek_keyword(FILE*, const char*)’:
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/io_utilities.cpp:49:15: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   49 |         fscanf(f, "%255s", s);
      |         ~~~~~~^~~~~~~~~~~~~~~
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/io_utilities.cpp: In function ‘bool cinolib::next_is_keyword(FILE*, const char*)’:
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/io_utilities.cpp:65:11: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   65 |     fscanf(f, "%255s", s);
      |     ~~~~~~^~~~~~~~~~~~~~~
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/io_utilities.cpp: In function ‘bool cinolib::eat_word(FILE*, char*)’:
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/io_utilities.cpp:77:11: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   77 |     fscanf(f, "%s", word);
      |     ~~~~~~^~~~~~~~~~~~~~~
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/io_utilities.cpp: In function ‘bool cinolib::eat_double(FILE*, double&)’:
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/io_utilities.cpp:87:11: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   87 |     fscanf(f, "%lf", &d);
      |     ~~~~~~^~~~~~~~~~~~~~
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/io_utilities.cpp: In function ‘bool cinolib::eat_int(FILE*, int&)’:
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/io_utilities.cpp:97:11: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   97 |     fscanf(f, "%d", &i);
      |     ~~~~~~^~~~~~~~~~~~~
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/io_utilities.cpp: In function ‘bool cinolib::eat_uint(FILE*, unsigned int&)’:
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/io_utilities.cpp:107:11: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  107 |     fscanf(f, "%d", &i);
      |     ~~~~~~^~~~~~~~~~~~~
[ 34%] Building CXX object _deps/cinolib-build/CMakeFiles/cinolib.dir/include/cinolib/io/read_CLI.cpp.o                                                   
[ 34%] Building CXX object _deps/cinolib-build/CMakeFiles/cinolib.dir/include/cinolib/io/read_CSV.cpp.o                                                   
[ 35%] Building CXX object _deps/cinolib-build/CMakeFiles/cinolib.dir/include/cinolib/io/read_DEYSUN2006.cpp.o                                            
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/read_DEYSUN2006.cpp: In function ‘void cinolib::read_DeyandSun2006(const char*, std::vector<double>&, std::vector<int>&, std::vector<double>&)’:
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/read_DEYSUN2006.cpp:64:11: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   64 |     fscanf(f, "%d %d\n", &nv, &ne);
      |     ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/read_DEYSUN2006.cpp:71:15: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   71 |         fscanf(f, "%lf %lf %lf", &x, &y, &z);
      |         ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/read_DEYSUN2006.cpp:83:15: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   83 |         fscanf(f, "%d %d", &v0, &v1);
      |         ~~~~~~^~~~~~~~~~~~~~~~~~~~~~
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/read_DEYSUN2006.cpp:92:15: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   92 |         fscanf(f, "%f", &dummyF);
      |         ~~~~~~^~~~~~~~~~~~~~~~~~
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/read_DEYSUN2006.cpp:93:15: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   93 |         fscanf(f, "%f", &dummyF);
      |         ~~~~~~^~~~~~~~~~~~~~~~~~
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/read_DEYSUN2006.cpp:94:15: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   94 |         fscanf(f, "%f", &dummyF);
      |         ~~~~~~^~~~~~~~~~~~~~~~~~
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/read_DEYSUN2006.cpp:95:15: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   95 |         fscanf(f, "%d", &dummyD1);
      |         ~~~~~~^~~~~~~~~~~~~~~~~~~
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/read_DEYSUN2006.cpp:96:55: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   96 |         for(unsigned int j = 0; j<dummyD1; ++j) fscanf(f, "%d", &dummyD2);
      |                                                 ~~~~~~^~~~~~~~~~~~~~~~~~~
[ 35%] Building CXX object _deps/cinolib-build/CMakeFiles/cinolib.dir/include/cinolib/io/read_HEDRA.cpp.o                                                 
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/read_HEDRA.cpp: In function ‘void cinolib::read_HEDRA(const char*, std::vector<cinolib::mat<3, 1, double> >&, std::vector<std::vector<unsigned int> >&, std::vector<std::vector<unsigned int> >&, std::vector<std::vector<bool> >&)’:
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/read_HEDRA.cpp:65:11: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   65 |     fscanf(fp, "%d %d %d", &nv, &nf, &np);
      |     ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/read_HEDRA.cpp:70:15: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   70 |         fscanf(fp, "%lf %lf %lf", &x, &y, &z);
      |         ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/read_HEDRA.cpp:77:15: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   77 |         fscanf(fp, "%d", &n_verts);
      |         ~~~~~~^~~~~~~~~~~~~~~~~~~~
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/read_HEDRA.cpp:83:19: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   83 |             fscanf(fp, "%d", &vid);
      |             ~~~~~~^~~~~~~~~~~~~~~~
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/read_HEDRA.cpp:92:15: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   92 |         fscanf(fp, "%d", &nf);
      |         ~~~~~~^~~~~~~~~~~~~~~
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/read_HEDRA.cpp:99:19: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   99 |             fscanf(fp, "%d", &fid);
      |             ~~~~~~^~~~~~~~~~~~~~~~
[ 35%] Building CXX object _deps/cinolib-build/CMakeFiles/cinolib.dir/include/cinolib/io/read_HEXEX.cpp.o                                                 
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/read_HEXEX.cpp: In function ‘void cinolib::read_HEXEX(const char*, std::vector<cinolib::mat<3, 1, double> >&, std::vector<unsigned int>&, std::vector<cinolib::mat<3, 1, double> >&)’:
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/read_HEXEX.cpp:65:11: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   65 |     fscanf(f,"%d\n", &nv);
      |     ~~~~~~^~~~~~~~~~~~~~~
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/read_HEXEX.cpp:69:15: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   69 |         fscanf(f,"%lf %lf %lf", &verts.at(vid).x(), &verts.at(vid).y(), &verts.at(vid).z());
      |         ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/read_HEXEX.cpp:73:11: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   73 |     fscanf(f,"%d\n", &nt);
      |     ~~~~~~^~~~~~~~~~~~~~~
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/read_HEXEX.cpp:79:15: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   79 |         fscanf(f,"%d %d %d %d %lf %lf %lf %lf %lf %lf %lf %lf %lf %lf %lf %lf",
      |         ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   80 |                &v0, &v1, &v2, &v3,
      |                ~~~~~~~~~~~~~~~~~~~
   81 |                &tets_param.at(4*tid+0).x(),
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   82 |                &tets_param.at(4*tid+0).y(),
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   83 |                &tets_param.at(4*tid+0).z(),
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   84 |                &tets_param.at(4*tid+1).x(),
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   85 |                &tets_param.at(4*tid+1).y(),
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   86 |                &tets_param.at(4*tid+1).z(),
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   87 |                &tets_param.at(4*tid+2).x(),
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   88 |                &tets_param.at(4*tid+2).y(),
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   89 |                &tets_param.at(4*tid+2).z(),
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   90 |                &tets_param.at(4*tid+3).x(),
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   91 |                &tets_param.at(4*tid+3).y(),
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   92 |                &tets_param.at(4*tid+3).z());
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ 36%] Building CXX object _deps/cinolib-build/CMakeFiles/cinolib.dir/include/cinolib/io/read_HYBRID.cpp.o                                                
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/read_HYBRID.cpp: In function ‘void cinolib::read_HYBDRID(const char*, std::vector<cinolib::mat<3, 1, double> >&, std::vector<std::vector<unsigned int> >&, std::vector<std::vector<unsigned int> >&, std::vector<std::vector<bool> >&)’:
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/read_HYBRID.cpp:66:11: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   66 |     fscanf(fp, "%d %d %d", &nv, &nf, &nc);
      |     ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/read_HYBRID.cpp:72:15: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   72 |         fscanf(fp, "%lf %lf %lf", &x, &y, &z);
      |         ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/read_HYBRID.cpp:79:15: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   79 |         fscanf(fp, "%d", &n_verts);
      |         ~~~~~~^~~~~~~~~~~~~~~~~~~~
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/read_HYBRID.cpp:85:19: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   85 |             fscanf(fp, "%d", &vid);
      |             ~~~~~~^~~~~~~~~~~~~~~~
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/read_HYBRID.cpp:94:15: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   94 |         fscanf(fp, "%d", &nf);
      |         ~~~~~~^~~~~~~~~~~~~~~
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/read_HYBRID.cpp:101:19: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  101 |             fscanf(fp, "%d", &fid);
      |             ~~~~~~^~~~~~~~~~~~~~~~
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/read_HYBRID.cpp:106:35: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  106 |         unsigned int dummy; fscanf(fp, "%d", &dummy);
      |                             ~~~~~~^~~~~~~~~~~~~~~~~~
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/read_HYBRID.cpp:110:19: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  110 |             fscanf(fp, "%d", &winding);
      |             ~~~~~~^~~~~~~~~~~~~~~~~~~~
[ 36%] Building CXX object _deps/cinolib-build/CMakeFiles/cinolib.dir/include/cinolib/io/read_IV.cpp.o                                                    
[ 37%] Building CXX object _deps/cinolib-build/CMakeFiles/cinolib.dir/include/cinolib/io/read_LIVESU2012.cpp.o                                            
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/read_LIVESU2012.cpp: In function ‘void cinolib::read_Livesu2012(const char*, std::vector<double>&, std::vector<int>&, std::vector<double>&)’:
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/read_LIVESU2012.cpp:76:11: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   76 |     fscanf(f, "ID Cx Cy Cz RADIUS #NEIGHBORS NEIGHBORS_LIST\n");
      |     ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/read_LIVESU2012.cpp:79:11: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   79 |     fscanf(f,"%d\n",&count);
      |     ~~~~~~^~~~~~~~~~~~~~~~~
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/read_LIVESU2012.cpp:91:15: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   91 |         fscanf(f, "%d %lf %lf %lf %lf %d ", &id, &x, &y, &z, &r, &n_arcs);
      |         ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/read_LIVESU2012.cpp:96:19: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   96 |             fscanf(f, "%d ", &nbr);
      |             ~~~~~~^~~~~~~~~~~~~~~~
[ 37%] Building CXX object _deps/cinolib-build/CMakeFiles/cinolib.dir/include/cinolib/io/read_MESH.cpp.o                                                  
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/read_MESH.cpp: In function ‘void cinolib::read_MESH(const char*, std::vector<cinolib::mat<3, 1, double> >&, std::vector<std::vector<unsigned int> >&, std::vector<int>&, std::vector<int>&)’:
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/read_MESH.cpp:108:18: warning: ignoring return value of ‘char* fgets(char*, int, FILE*)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  108 |             fgets(line, 1024, f);
      |             ~~~~~^~~~~~~~~~~~~~~
[ 38%] Building CXX object _deps/cinolib-build/CMakeFiles/cinolib.dir/include/cinolib/io/read_OBJ.cpp.o                                                   
[ 38%] Building CXX object _deps/cinolib-build/CMakeFiles/cinolib.dir/include/cinolib/io/read_OFF.cpp.o                                                   
[ 39%] Building CXX object _deps/cinolib-build/CMakeFiles/cinolib.dir/include/cinolib/io/read_STL.cpp.o                                                   
[ 39%] Building CXX object _deps/cinolib-build/CMakeFiles/cinolib.dir/include/cinolib/io/read_TAGLIASACCHI2012.cpp.o                                      
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/read_TAGLIASACCHI2012.cpp: In function ‘void cinolib::read_Tagliasacchi2012(const char*, std::vector<double>&, std::vector<int>&, std::vector<double>&)’:
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/read_TAGLIASACCHI2012.cpp:64:11: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   64 |     fscanf(f,"# D:%d NV:%d NE:%d\n", &dummy, &nv, &ne);
      |     ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/read_TAGLIASACCHI2012.cpp:71:15: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   71 |         fscanf(f, "v %lf %lf %lf\n", &x, &y, &z);
      |         ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/read_TAGLIASACCHI2012.cpp:81:15: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   81 |         fscanf(f, "e %d %d\n", &v0, &v1);
      |         ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
[ 40%] Building CXX object _deps/cinolib-build/CMakeFiles/cinolib.dir/include/cinolib/io/read_TET.cpp.o                                                   
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/read_TET.cpp: In function ‘void cinolib::read_TET(const char*, std::vector<double>&, std::vector<unsigned int>&)’:
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/read_TET.cpp:60:10: warning: ignoring return value of ‘char* fgets(char*, int, FILE*)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   60 |     fgets(line,1024,fp);
      |     ~~~~~^~~~~~~~~~~~~~
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/read_TET.cpp:63:10: warning: ignoring return value of ‘char* fgets(char*, int, FILE*)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   63 |     fgets(line,1024,fp);
      |     ~~~~~^~~~~~~~~~~~~~
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/read_TET.cpp:68:14: warning: ignoring return value of ‘char* fgets(char*, int, FILE*)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   68 |         fgets(line, 1024, fp);
      |         ~~~~~^~~~~~~~~~~~~~~~
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/read_TET.cpp:82:14: warning: ignoring return value of ‘char* fgets(char*, int, FILE*)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   82 |         fgets(line, 1024, fp);
      |         ~~~~~^~~~~~~~~~~~~~~~
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/read_TET.cpp: In function ‘void cinolib::read_TET(const char*, std::vector<cinolib::mat<3, 1, double> >&, std::vector<std::vector<unsigned int> >&)’:
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/read_TET.cpp:116:10: warning: ignoring return value of ‘char* fgets(char*, int, FILE*)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  116 |     fgets(line,1024,fp);
      |     ~~~~~^~~~~~~~~~~~~~
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/read_TET.cpp:119:10: warning: ignoring return value of ‘char* fgets(char*, int, FILE*)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  119 |     fgets(line,1024,fp);
      |     ~~~~~^~~~~~~~~~~~~~
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/read_TET.cpp:127:14: warning: ignoring return value of ‘char* fgets(char*, int, FILE*)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  127 |         fgets(line, 1024, fp);
      |         ~~~~~^~~~~~~~~~~~~~~~
/home/acae/00Github/HexBox/zcc_build/_deps/cinolib-src/include/cinolib/io/read_TET.cpp:138:14: warning: ignoring return value of ‘char* fgets(char*, int, FILE*)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  138 |         fgets(line, 1024, fp);
      |         ~~~~~^~~~~~~~~~~~~~~~
[ 40%] Building CXX object _deps/cinolib-build/CMakeFiles/cinolib.dir/include/cinolib/io/read_VTK.cpp.o

**Comment by zcc2xj** [comment]
[gui.zip](https://github.com/cg3hci/HexBox/files/14556127/gui.zip)

**Comment by zcc2xj** [comment]
Linux acae-e42 6.5.0-25-generic #25~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Feb 20 16:09:15 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

**Comment by gcherchi** [comment]
Hi,
I cloned the repo again and tried it on my computer, and the multi-face selection works well (I need to use cmd instead of ctrl since I'm using a Mac).
I don't have the possibility to test it on other OSs at the moment, but I will do so as soon as I or one of my collaborators has some other PC to test it. 
Thank you.

**Comment by zcc2xj** [comment]
> Hi, I cloned the repo again and tried it on my computer, and the multi-face selection works well (I need to use cmd instead of ctrl since I'm using a Mac). I don't have the possibility to test it on other OSs at the moment, but I will do so as soon as I or one of my collaborators has some other PC to test it. Thank you.

Wow, you replys sof fast. Thank you.
and I tried Windows key which means your "cmd" key ,and it works.
so you need change tutorials

**Comment by gcherchi** [comment]
Thanks for your suggestion.
I added the models in the paper to this repo.

**Comment by MaguRaam** [comment]
Hi, I cannot select multiple faces using the ctrl + mouse left. I have installed the HexBox on the wsl side.

**Comment by gcherchi** [comment]
Hi,
if you are using Windows you could try the Windows key, as reported by zcc2xj some comment above.

**Comment by MaguRaam** [comment]
Great, this works for Windows installation.
