### ISSUE TITLE
Can't load other meshes

### ISSUE THREAD

**Issue by Zhumin-collab** [cg3hci/HexBox#17]
hello,there is no errors in compiling process,but i can't load other meshes
<img width="1172" alt="微信图片_20240523221929" src="https://github.com/cg3hci/HexBox/assets/67891274/a92dba67-0c13-49d9-a227-a2db0a6f6e6c">

**Comment by gcherchi** [comment]
Hi Zhumin,
can you send us the mesh you are trying to upload?

**Comment by Zhumin-collab** [comment]
thanks，just any meshes in  models folder

**Comment by mlivesu** [comment]
Importing an existing hexmesh is not currently supported, as we would need to also import (or derive) the tree of operations associated to it. Mesh loading is intended as a way to import a surface (triangle) mesh that provides a target reference geometry for boundary projection.

**Comment by gcherchi** [comment]
Ok, I see the problem.
Meshes in the "models" folder have been modeled with HexBox and exported as final meshes (.mesh files). In HexBox you cannot import generic hexahedral meshes. Importing existing hexmeshes is not currently supported, as we would need to also import (or derive) the DAG of associated operations.
If you want to import hex-meshes generated with HexBox you must save them as .hmp file (a format including both the geometry and the DAG of the modeling session).
Alternatively, you can upload a surface mesh and use it as target mesh to guide your modeling session from scratch (the surface mesh must be uploaded from the "Target mesh" menu option).
