### ISSUE TITLE
Input Mesh formats

### ISSUE THREAD

**Issue by MaguRaam** [cg3hci/HexBox#18]
Hello,

I am attempting to use the HexBox GUI tool to convert a surface mesh in STL format into a hexahedral mesh. However, I encountered a couple of issues:

Loading Surface Mesh in STL Format: Is it possible to load a surface mesh in STL format and generate a hexahedral mesh as output using HexBox?

Crash when Loading .mesh Format: I tried to load a mesh file in .mesh format, as provided in the example, but the GUI crashed unexpectedly.

Thank you for your assistance in resolving this issue.

**Comment by gcherchi** [comment]
Hi,
With HexBox, you can upload a surface mesh (I suggest you use .obj files) to use as a target mesh to guide you during the modeling session. Notice that HexBox is a tool intended for manual hexahedral mesh modeling, not to automatically convert a surface into a hex mesh.

Regarding the crash reported when uploading .mesh, you may find a possible solution here: https://github.com/cg3hci/HexBox/issues/17.

All the bests :)
