### ISSUE TITLE
fail to show gui.exe

### ISSUE THREAD

**Issue by zyyue99** [cg3hci/HexBox#19]
Thank you so much for sharing the code. But I ran into some problems. After I successfully built the project, my gui.exe file opened without any toolbars. Could you tell me the solution?
<img width="350" alt="gui" src="https://github.com/user-attachments/assets/8a24891d-ac14-4bf7-8c03-50e509ce3ab4">

**Comment by gcherchi** [comment]
Hi,
the toolbar appears by pressing the "tab" key :)

**Comment by zyyue99** [comment]
> Hi, the toolbar appears by pressing the "tab" key :)

Sorry, I can't find the "tab" key. My gui doesn't seem to be generating properly, I don't know why.
