### ISSUE TITLE
display issues

### ISSUE THREAD

**Issue by gpbonneau** [cg3hci/HexBox#2]
The code compiled smoothly but there are displaying issues, see the two screenshots below. The overlay is shifted, and the cube appears in a small viewport. Maybe some issues related to the Retina display?

OS Ventura 13.1
2,8 GHz Intel Core i7 4 cores
Intel Iris Plus Graphics 655 1536 Mo
cmake version 3.26.4
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: x86_64-apple-darwin22.2.0
Thread model: posix

Retina display 13,3 inches (2560 × 1600)

<img width="699" alt="Capture d’écran 2023-07-04 à 17 51 28" src="https://github.com/cg3hci/HexBox/assets/12672526/1117e611-f28e-4fc0-8f7a-4ed7e7a157fa">
<img width="697" alt="Capture d’écran 2023-07-04 à 17 51 00" src="https://github.com/cg3hci/HexBox/assets/12672526/1869674f-4b4b-43e0-9804-dadf1be51899">

**Comment by francescozoccheddu** [comment]
Hi,
thank you for reporting this! 😉 
I added a temporary fix [here](https://github.com/cg3hci/HexBox/commit/7a49bc16ba417c55fe23baf4b9316c3a24186b20).
Let us know if you still face the issue.

**Comment by gpbonneau** [comment]
Works like a charm now!
Great work and great talk at SGP 2023 :-)
