### ISSUE TITLE
Cannot extrude between two  adjacent faces

### ISSUE THREAD

**Issue by zyyue99** [cg3hci/HexBox#22]
Hello, I am unable to perform the “Extrusion” operation between two adjacent faces. Could you tell me what the reason might be?

**Comment by mlivesu** [comment]
are the two faces part of the same hexahedron?

**Comment by zyyue99** [comment]
> are the two faces part of the same hexahedron?

No, the two faces belong to different hexahedron, they share the same edge. Thank you for your reply.

**Comment by zyyue99** [comment]
> I am not sure whether you are reporting an issue regarding a specific mesh, or if you are unable to extrude _any_ pair of adjacent faces. If the latter, I suggest you take a look at the official [tutorial](https://github.com/cg3hci/HexBox/blob/master/tutorials.md). Otherwise, you should share with us the specific problematic model, so that we can reproduce the experiment

I am unable to extrude any pair of adjacent faces. I followed the tutorial by using Ctrl+MouseLeft and then by pressing the key E, but it didn't work.

**Comment by zyyue99** [comment]
> I am not sure whether you are reporting an issue regarding a specific mesh, or if you are unable to extrude _any_ pair of adjacent faces. If the latter, I suggest you take a look at the official [tutorial](https://github.com/cg3hci/HexBox/blob/master/tutorials.md). Otherwise, you should share with us the specific problematic model, so that we can reproduce the experiment

I am unable to extrude any pair of adjacent faces. I followed the tutorial by using Ctrl+MouseLeft and then by pressing the key E, but it didn't work.

**Comment by gcherchi** [comment]
Use cmd instead of ctrl in you are using a mac
