### ISSUE TITLE
Issue with GUI after compilation 

### ISSUE THREAD

**Issue by otaolafranc** [cg3hci/HexBox#7]
Hello,
I just downloaded and installed HexBox using the following lines in tuxedOS 2:
`#installing dependencies
sudo apt-get update -y
sudo apt-get install -y libxi-dev
sudo apt-get install -y libxcursor-dev
sudo apt-get install -y libxinerama-dev
sudo apt-get install -y libxrandr-dev

#instaling HexBox
mkdir build
cd build
cmake ..
cmake --build .
`
when I run the interface using `build/gui/gui`
I am getting the following windows (which does not have the tools as it is shown in the publication):
![image](https://github.com/cg3hci/HexBox/assets/44319721/181a2731-da1d-4886-8d76-252ba9db58f7)

**Comment by gcherchi** [comment]
Hi,
if you press the tab button the tools should appear.
BTW, we are changing some of the commands in the terminal. We plan to commit in a few days.
Bests,
Gianmarco
